name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main
    
env:
  AWS_REGION: ${{vars.AWS_REGION}}
  ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
  ECS_SERVICE: ${{vars.ECS_SERVICE}}
  ECS_CLUSTER: ${{vars.ECS_CLUSTER}}
  ECS_TASK_DEFINITION: ${{vars.ECS_TASK_DEFINITION}}
  CONTAINER_NAME: ${{vars.CONTAINER_NAME}}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{env.ECS_TASK_DEFINITION}}
          container-name: ${{env.CONTAINER_NAME}}
          image: salim8898/cicd-simple-web:latest
